import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Fonts via <link> para evitar next/font */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Geist&amp;family=Geist+Mono&amp;display=swap"
        />
      </head>
      <body suppressHydrationWarning className="antialiased font-geist font-geist-mono">
        {children}
      </body>
    </html>
  );
}